name: CI

on:
  pull_request:
    branches: [ group-* ]   # PR base branch must match these
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main, group-*, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency install."
          fi

      - name: Run tests (tolerate 'no tests collected')
        env:
          PYTHONPATH: ${{ github.workspace }}
        shell: bash
        run: |
          set +e
          pytest -q
          code=$?
          set -e
          if [ "$code" -eq 5 ]; then
            echo "No tests collected (pytest exit 5). Treating as success."
            exit 0
          fi
          exit "$code"
