name: CI

on:
  pull_request:
    branches: [ group-* ]   # PR base branch must match these
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main, group-*, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency install."
          fi

      - name: Run tests (only if tests exist)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          if compgen -G "tests/**/*.py" > /dev/null || compgen -G "tests/*.py" > /dev/null; then
            pytest -q
          else
            echo "No tests found. Skipping pytest."
          fi
